### PR TITLE
Allow state type to have lifetime parameters

### PR DESCRIPTION
**Pull request by alan-j-hu**
This is a preliminary PR to implement https://github.com/osa1/lexgen/issues/52.

### CODE REVIEW

**Review by osa1 — COMMENTED** [review]
Implementation LGTM.

Should we have a test with state with `'input` and another lifetime? Maybe something like `struct State<'a, 'b> { strings: &'a mut [&'b str] }`.

It seems like in the tests `'input` is always `'static`. Should we test the case where `'input` is not `'static`? In practice `'input` is only `'static` in tests, in actual uses it's never `'static`. So it might be a good idea to make sure the generated code makes sense and is usable when input lifetime is not `'static`.

**Comment by alan-j-hu** [comment]
> It seems like in the tests `'input` is always `'static`. Should we test the case where `'input` is not `'static`? In practice `'input` is only `'static` in tests, in actual uses it's never `'static`. So it might be a good idea to make sure the generated code makes sense and is usable when input lifetime is not 'static.

I've just added a test for this.

As this PR stands, the generated code emits compiler warnings because of the `'input: 'static` hack due to https://github.com/osa1/lexgen/issues/54. Shall this PR be merged, then the `Default` issue fixed separately?

**Review by osa1 — APPROVED** [review]
LGTM, but we should resolve these two:

- I see these warnings generated when building the tests:
  ```
  warning: unnecessary lifetime parameter `'input`
      --> crates/lexgen/tests/tests.rs:1188:5
       |
  1188 | /     lexer! {
  1189 | |         Lexer(State<'input>) -> ();
  1190 | |
  1191 | |         rule Init {
  ...    |
  1206 | |         }
  1207 | |     }
       | |_____^
       |
       = help: you can use the `'static` lifetime directly, in place of `'input`
       = note: this warning originates in the macro `lexer` (in Nightly builds, run with -Z macro-backtrace for more info)
  ```
  I didn't investigate further but I confirmed that the same warnings were generated before me merging origin/main into your branch (thanks for allowing it btw), so I didn't introduce these.

- When I build a downstream project with this PR I get this error:
  ```
  Compiling lexgen v0.11.0 (/home/omer/rust/lexgen/crates/lexgen)
  error[E0432]: unresolved import `syn::visit`
    --> /home/omer/rust/lexgen/crates/lexgen/src/dfa/codegen.rs:20:10
     |
  20 | use syn::visit::Visit;
     |          ^^^^^ could not find `visit` in `syn`
  ```
  If I enable "visit" feature in `syn` dependency it builds.

  I don't understand why and how it works when building lexgen and the tests without this feature though..

**Comment by osa1** [comment]
Thanks!

**Pull request merged**
