### PR TITLE
Implement [^'0'-'9'] syntax

### PR DESCRIPTION
**Pull request by seanyoung**

### CODE REVIEW

**Review by osa1 — COMMENTED** [review]
We can already do this today with `#`, no? This should be the same as your test lexer:

```rust
lexer! {
    Lexer -> usize;

    $ = 1,
    'a' = 2,
    _ # ['b'-'z'] = 3,
    _ = 4,
}
```

Am I missing anything?

**Comment by seanyoung** [comment]
> We can already do this today with `#`, no? This should be the same as your test lexer:
> 
> ```rust
> lexer! {
>     Lexer -> usize;
> 
>     $ = 1,
>     'a' = 2,
>     _ # ['b'-'z'] = 3,
>     _ = 4,
> }
> ```
> 
> Am I missing anything?

Yes, you are right that it can be done with the existing syntax. It's just convenience syntax, when I first looked at lexgen I thought, why can't I do `[^...]`?  This is how this is usually expressed, and not via `_ # ...`. The resulting DFA will be exactly the same of course.

**Comment by osa1** [comment]
Adding new syntax is often quite costly. I wrote about this a while ago on my blog: https://osa1.net/posts/2020-01-22-no-small-syntax-extensions.html it's in a different context but most of the points apply here. In this particular case, I don't think this syntax will have much benefit given that `_ # ...` syntax not too much more verbose and it does the same thing. So it's extra complexity (for lexgen users and developers) without much benefit.

Do you find the lack of this syntax to be a problem in practice?

**Comment by seanyoung** [comment]
> Do you find the lack of this syntax to be a problem in practice?

Not really. I was just toying with lexgen.

**Pull request closed without merging**
